### PR TITLE
make test/oop.js

### PR DESCRIPTION
**Pull request by KHYehor**
I made test for oop.js, also modified it with binding context of object.

What is about other tests, they are complete, isn't it?

### CODE REVIEW

**Comment by belochub** [comment]
@KHYehor you can check test coverage report to see if there are other functions that are not yet covered by unit tests.

**Comment by KHYehor** [comment]
@belochub What `test coverage report` do you mean? That `override` test fail?

**Comment by belochub** [comment]
@KHYehor you can use [Istanbul tool](https://istanbul.js.org/), for example, to obtain a test coverage report:
```sh
$ npx nyc metatests test/
```

**Comment by belochub** [comment]
Closed in favor of https://github.com/metarhia/common/pull/301.

**Pull request closed without merging**
