### PR TITLE
Implement version check and compare functions

### PR DESCRIPTION
**Pull request by SemenchenkoVitaliy**
Closes: https://github.com/metarhia/common/issues/253

/cc @lundibundi @nechaido @belochub

### CODE REVIEW

**Comment by belochub** [comment]
Can't we just use [the `semver` package](http://npmjs.com/semver) for this?

**Comment by SemenchenkoVitaliy** [comment]
@belochub This would bring new external dependencies.

**Comment by belochub** [comment]
@SemenchenkoVitaliy and what's the problem with that?

**Comment by SemenchenkoVitaliy** [comment]
@belochub I thought that we will remove most external dependencies from Metarhia stack and replace them with our own in the future. If this is not the case then I think that this PR can be closed.

**Comment by tshemsedinov** [comment]
I think it will be better to remove `semver` dependency and any other dependencies in future. We are going to create as independent infrastructure as possible. We may use `devDependencies` without limitations but if we can create replacement of `dependencies` quickly it is preferable.

**Comment by belochub** [comment]
Closing for now since there is no need to add this kind of public API to this package at the moment.

**Pull request closed without merging**
