### PR TITLE
lib: code style optimizations

### PR DESCRIPTION
**Pull request by tshemsedinov**
* Change module.exports to lambdas
* Remove `lib/data.js` from `.eslintignore` (added to avoid conflicts) and add required indentation to `lib/data.js`
* Add intermediate variables and rename variables

### CODE REVIEW

**Comment by aqrln** [comment]
I wonder why Travis ignores this PR.

**Comment by aqrln** [comment]
Ah, I see. It wasn't configured to build the repo.

**Comment by aqrln** [comment]
Reopened to trigger a build. Sorry, that's the only way in Travis :)

**Comment by aqrln** [comment]
Sorry for spamming repo watchers' emails, but here we go again.

Now Travis seems to work :)

**Comment by tshemsedinov** [comment]
Landed in 7b13f1e070f39c49951d53daa4e56847e72670ac

**Pull request closed without merging**
