### PR TITLE
Add curry function

### PR DESCRIPTION
**Pull request by nechaido**
As it was requested in #10 I add an implementation of `curry()` function.
I think it is appropriate to put it into `functional` submodule.

### CODE REVIEW

**Comment by nechaido** [comment]
@tshemsedinov changed

**Comment by tshemsedinov** [comment]
Can't see @nechaido, mb you didn't add file to commit

**Comment by nechaido** [comment]
@tshemsedinov yep, my fault

**Comment by tshemsedinov** [comment]
Landed in 49959f0819f57b53e7aa9a39e81c4fbebbe37ecc

**Pull request closed without merging**
