### PR TITLE
Reimplement merge function

### PR DESCRIPTION
**Pull request by IvanHonchar**
Now merge function works faster (n * log(n) instead of n * n) and result array has no duplicates even if first array in args has.

### CODE REVIEW

**Comment by tshemsedinov** [comment]
@IvanHonchar see https://github.com/metarhia/maojian/issues/13

**Comment by tshemsedinov** [comment]
Here is another optimized implementation: `const merge = (...arrays) => [...(new Set([].concat(arrays)))];`
But do not remove your, we need to compare. Prepare as multiple implementations as you and compare performance on different datasets (large and small, homogeneous and heterogeneous)

**Comment by IvanHonchar** [comment]
Using this code https://github.com/IvanHonchar/maojian/tree/master/test/merge-test and nodejs v9.2.0 I got following results:
```
500 arrays 500 elements each, random numbers [1..250000]

loopsAndSet.....................57680355.......min
forEachAndSet...................64117144......+11%
concatAndSet....................75497470......+31%
loopsAndArrays...............48845148701...+84582%

--------------------------------------------------
500 arrays 500 elements each, random numbers [1..500]

loopsAndSet.....................13088818.......min
forEachAndSet...................15618833......+19%
concatAndSet....................28131897.....+115%
loopsAndArrays.................186218595....+1323%

--------------------------------------------------
1000 arrays 10 elements each, random numbers [1..10000]

forEachAndSet....................1812319.......min
concatAndSet.....................2048867......+13%
loopsAndSet......................2292262......+26%
loopsAndArrays..................77983252....+4203%

--------------------------------------------------
1000 arrays 10 elements each, random numbers [1..10]

loopsAndSet.......................307438.......min
loopsAndArrays....................549642......+79%
forEachAndSet.....................617246.....+101%
concatAndSet......................996149.....+224%

--------------------------------------------------
10 arrays 1000 elements each, random numbers [1..10000]

loopsAndSet......................1319502.......min
forEachAndSet....................1464483......+11%
concatAndSet.....................2152054......+63%
loopsAndArrays..................79202611....+5902%

--------------------------------------------------
10 arrays 1000 elements each, random numbers [1..10]

loopsAndSet.......................281102.......min
forEachAndSet.....................425407......+51%
loopsAndArrays....................506867......+80%
concatAndSet......................714052.....+154%

--------------------------------------------------
10 arrays 10 elements each, random numbers [1..100]

loopsAndArrays...................1131878.......min
loopsAndSet......................1238703.......+9%
forEachAndSet....................1481591......+31%
concatAndSet.....................2064408......+82%
```
As we can see, the fastest in average implementation is with using loops and Set.

**Comment by tshemsedinov** [comment]
Landed in 10d2854

**Pull request closed without merging**
